# Generated by Django 3.1.4 on 2020-12-30 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.IntegerField(choices=[('1', 'New'), ('2', 'Sent'), ('3', 'Returned'), ('4', 'Failed')], default='1'),
        ),
    ]
