# Generated by Django 3.1.4 on 2021-02-27 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('1', 'Na dobirku'), ('2', 'Platba kartou')], default='1', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name='Shipping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('carrier', models.CharField(choices=[('1', 'Česká pošta'), ('2', 'Slovenská pošta')], default='1', max_length=2)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.payment'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='carts.shipping'),
        ),
    ]
