# Generated by Django 3.1.4 on 2021-02-27 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20210227_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='type',
        ),
        migrations.RemoveField(
            model_name='shipping',
            name='carrier',
        ),
    ]
