# Generated by Django 3.1.4 on 2021-02-27 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20210227_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.payment'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='carts.shipping'),
        ),
    ]
