# Generated by Django 3.1.4 on 2021-02-27 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_auto_20210227_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='payment',
            field=models.CharField(choices=[('1', 'Na dobirku'), ('2', 'Platba kartou')], default='1', max_length=1),
        ),
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.CharField(choices=[('1', 'Česká pošta'), ('2', 'Slovenská pošta')], default='1', max_length=1),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
        migrations.DeleteModel(
            name='Shipping',
        ),
    ]
