# Generated by Django 3.1.4 on 2021-03-16 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_productvariation_content'),
        ('carts', '0005_auto_20210227_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='variation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='products.productvariation'),
            preserve_default=False,
        ),
    ]
