# Generated by Django 3.1.3 on 2020-11-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('postcode', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('code', models.CharField(max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5)),
                ('expiry', models.DateTimeField()),
                ('created', models.DateTimeField()),
                ('counter', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash', models.CharField(default='TEST', max_length=11)),
                ('shipping', models.CharField(choices=[('1', 'Česká pošta')], default='1', max_length=1)),
                ('payment', models.CharField(choices=[('1', 'Na dobirku'), ('2', 'Platba kartou')], default='1', max_length=1)),
                ('cart_items', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='product.product')),
                ('customer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.customer')),
                ('discount', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='cart.discount')),
            ],
        ),
    ]
