# Generated by Django 3.1.4 on 2020-12-19 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_auto_20201219_1835'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='hash',
        ),
    ]
