# Generated by Django 3.1.4 on 2020-12-26 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_auto_20201226_1323'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='regular_price',
        ),
        migrations.RemoveField(
            model_name='cartitem',
            name='sale_price',
        ),
    ]
