# Generated by Django 3.1.4 on 2020-12-19 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_auto_20201212_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='hash',
            field=models.CharField(max_length=11),
        ),
    ]
