# Generated by Django 3.1.4 on 2020-12-25 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
        ('cart', '0006_remove_cart_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items',
            field=models.ManyToManyField(to='product.Product'),
        ),
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
