# Generated by Django 3.1.4 on 2020-12-30 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_auto_20201226_2110'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='shipping',
            field=models.CharField(choices=[('1', 'Česká pošta'), ('2', 'Slovenská pošta')], default='1', max_length=1),
        ),
    ]
