# Generated by Django 3.1.4 on 2021-02-02 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='short_name',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
