# Generated by Django 3.1.4 on 2021-02-07 22:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now=True)),
                ('state', models.IntegerField(choices=[('0', 'Abandoned'), ('1', 'New'), ('2', 'Dispatched'), ('3', 'Delivered'), ('4', 'Returned'), ('5', 'Failed')], default='0')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.cart')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.customer')),
            ],
        ),
    ]
