# Generated by Django 3.1.4 on 2021-02-07 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210207_2256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='state',
            field=models.CharField(choices=[('0', 'Abandoned'), ('1', 'New'), ('2', 'Dispatched'), ('3', 'Delivered'), ('4', 'Returned'), ('5', 'Failed')], default='0', max_length=255),
        ),
    ]
