# Generated by Django 3.1.4 on 2020-12-30 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20201230_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='order_status',
            new_name='order_state',
        ),
    ]
