# Generated by Django 3.1.4 on 2021-02-14 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='short_name',
            new_name='export_name',
        ),
    ]
