# Generated by Django 3.1.4 on 2021-02-18 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_upsell',
            field=models.BooleanField(default=False),
        ),
    ]
