# Generated by Django 3.1.4 on 2021-03-07 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20210307_1229'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='facebook_remarketing_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='google_remarketing_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/<built-in function id>'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/<built-in function id>'),
        ),
        migrations.CreateModel(
            name='ProductTab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
        ),
    ]
