# Generated by Django 3.1.4 on 2021-03-07 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20210307_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='facebook_remarketing_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='google_remarketing_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='products/'),
        ),
    ]
