# Generated by Django 3.1.4 on 2021-03-07 15:17

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20210307_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producttab',
            old_name='headline',
            new_name='name',
        ),
        migrations.AddField(
            model_name='producttab',
            name='internal_name',
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
